from datetime import datetime, timedelta

from reportlab.lib import colors
from reportlab.lib import enums
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle,
)

def Export(mission, startTime, timelines):
        doc = SimpleDocTemplate(
            "FinalStrategy.pdf",
            leftMargin=20 * mm,
            rightMargin=20 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
        )

        styles = getSampleStyleSheet()

        styles.add(
            ParagraphStyle(
                "ReportTitle",
                parent=styles["Title"],
                fontSize=26,
                leading=30,
                alignment=enums.TA_LEFT,
            )
        )

        styles.add(
            ParagraphStyle(
                "SectionTitle",
                parent=styles["Heading1"],
                textColor=colors.HexColor("#1F4E79"),
            )
        )

        styles.add(
            ParagraphStyle(
                "MetricValue",
                parent=styles["Heading2"],
                fontSize=20,
                textColor=colors.HexColor("#1F4E79"),
            )
        )

        story = []

        # ==========================================================
        # COVER PAGE
        # ==========================================================

        story.append(Spacer(1, 60))

        story.append(
            Paragraph(
                "FLEETS-ONLINE",
                styles["Heading2"],
            )
        )

        story.append(Spacer(1, 12))

        story.append(
            Paragraph(
                "Logistical Mission Strategy Generator",
                styles["ReportTitle"],
            )
        )

        story.append(
            Paragraph(
                "Final Mission Strategy Report",
                styles["Heading2"],
            )
        )

        story.append(Spacer(1, 30))
        story.append(
            Paragraph(
                f"<b>Mission ID:</b> ID",
                styles["BodyText"],
            )
        )

        story.append(
            Paragraph(
                f"<b>Generated:</b> {datetime.now():%Y-%m-%d %H:%M}",
                styles["BodyText"],
            )
        )

        story.append(PageBreak())

        # ==========================================================
        # EXECUTIVE SUMMARY
        # ==========================================================

        story.append(
            Paragraph(
                "Executive Summary",
                styles["SectionTitle"],
            )
        )

        story.append(Spacer(1, 8))

        story.append(
            Paragraph(
                f"""
                This strategy was generated by the Logistical Mission
                Strategy Generator. The selected plan completes all
                transport and work operations for {mission.work_jobs[0].name} while balancing mission performance indicators according to the user preferences;
                operational cost ({mission.mission_preferences[0] * 100:.1f} %), execution time ({mission.mission_preferences[1] * 100:.1f} %) and environmental
                impact ({mission.mission_preferences[2] * 100:.1f} %).
                """,
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 15))

        kpi_table = Table(
            [
                ["Total Cost", r"CO_2", "NOx"],
                [
                    f"€ {mission.mission_cost:,.0f} eur",
                    # f"{mission.total_duration_hours:.1f} h",
                    f"{mission.mission_CO2:.1f} kg",
                    f"{mission.mission_NOx:.1f} kg",
                ],
            ],
            colWidths=[60 * mm, 50 * mm, 50 * mm],
        )

        kpi_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ]
            )
        )

        story.append(kpi_table)

        story.append(Spacer(1, 25))

        # ==========================================================
        # FLEET OVERVIEW
        # ==========================================================

        story.append(
            Paragraph(
                "Fleet Overview",
                styles["SectionTitle"],
            )
        )

        machine_data = [
            [
                "Name",
                "Type",
                "Build year",
                "Fuel",
                "Emission class",
                "Cost",
                r"CO_2",
                "NOx",
                # "Hours",
            ]
        ]
        machines = []
        for transport_job in mission.transport_jobs:
            machine = transport_job.transporting_vehicle
            if machine.hours_used > 0:
                machines.append(machine)
                machine_data.append(
                    [
                        machine.machine_id,
                        machine.machine_type,
                        str(machine.build_year),
                        machine.energy_source,
                        machine.emission_class,
                        f"€{machine.individualCost:,.0f}",
                        f"{machine.individualCO2:.1f}",
                        f"{machine.individualNOX:.1f}",
                        # f"{machine.total_time:.1f}",
                    ]
                )
        for work_job in mission.work_jobs:
            for machine in work_job.assigned_vehicles:
                if machine not in machines:
                    machine_data.append(
                        [
                            machine.machine_id,
                            machine.machine_type,
                            str(machine.build_year),
                            machine.energy_source,
                            machine.emission_class,
                            f"€{machine.individualCost:,.0f}",
                            f"{machine.individualCO2:.1f}",
                            f"{machine.individualNOX:.1f}",
                            # f"{machine.total_time:.1f}",
                        ]
                    )

        machine_table = Table(machine_data, repeatRows=1)

        machine_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1),
                     [colors.white, colors.HexColor("#F6F8FA")]),
                ]
            )
        )

        story.append(machine_table)

        story.append(PageBreak())

        # ==========================================================
        # TRANSPORT JOBS
        # ==========================================================

        story.append(
            Paragraph(
                "Transport Operations",
                styles["SectionTitle"],
            )
        )

        transport_data = [
            [
                "Origin",
                "Destination",
                "Machine",
                "Start",
                "Arrival",
            ]
        ]

        for job in mission.transport_jobs:
            if job.routeDuration > 1:
                transport_data.append(
                    [
                        str(job.begin_location_gps),
                        str(job.end_location_gps),
                        job.transporting_vehicle.machine_id,
                        str(startTime),
                        str(startTime + timedelta(minutes=job.routeDuration)),
                    ]
                )

        transport_table = Table(
            transport_data,
            repeatRows=1,
        )

        transport_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )

        story.append(transport_table)

        story.append(Spacer(1, 25))

        # ==========================================================
        # WORK OPERATIONS
        # ==========================================================

        story.append(
            Paragraph(
                "Work Operations",
                styles["SectionTitle"],
            )
        )

        work_data = [
            [
                "Machine",
                "Location",
                # "Start",
                # "Finish",
                "Hours used"
            ]
        ]

        for job in mission.work_jobs:
            for m in job.assigned_vehicles:
                work_data.append(
                    [
                        m.machine_id,
                        str(job.gps_location),
                        str(m.hours_used),
                        # job.finish_time,
                    ]
                )
            for t in job.assigned_tools:
                work_data.append(
                    [
                        t.machine_id,
                        str(job.gps_location),
                        str(m.hours_used)
                        # job.finish_time,
                    ]
                )

        work_table = Table(work_data, repeatRows=1)

        work_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )

        story.append(work_table)


        # ================
        # PLANNING
        # ================

        story.append(
            Paragraph(
                "Planning",
                styles["SectionTitle"],
            )
        )

        planning_data = [
            [
                "Machine",
                "Job",
                "Start",
                "Finish",
                # "Hours used"
            ]
        ]

        for action in timelines:
            if action[0].machine_type == "Truck":
                try:
                    if action[0].contents.contents != []:
                        planning_data.append([action[0].machine_id, f"Truck moving {action[0].contents.contents[0].machine_type} to worksite", action[1], action[2]])
                    else:
                        planning_data.append([action[0].machine_id, f"Truck picking up needed machine", action[1], action[2]])
                except:
                    planning_data.append([action[0].machine_id, f"Truck picking up needed machine", action[1], action[2]])
            elif action[3] == "transport":
                planning_data.append([action[0].machine_id, f"{action[0].machine_type} moving to worksite", action[1], action[2]])
            else:
                planning_data.append([action[0].machine_id, f"{action[0].machine_type} working", action[1], action[2]])

        planning_table = Table(planning_data, repeatRows=1)

        planning_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )

        story.append(planning_table)



        story.append(PageBreak())

        # ==========================================================
        # ENVIRONMENTAL IMPACT
        # ==========================================================

        story.append(
            Paragraph(
                "Environmental Impact",
                styles["SectionTitle"],
            )
        )

        emissions_data = [
            ["Machine", r"CO_2 (kg)", "NOx (kg)", "Work type"]
        ]
        machines = []
        for work_job in mission.work_jobs:
            for machine in work_job.assigned_vehicles:
                machines.append(machine)
                emissions_data.append(
                    [
                        machine.machine_id,
                        f"{machine.individualCO2:.1f}",
                        f"{machine.individualNOX:.1f}",
                        "Work"
                    ]
                )
        for transport_job in mission.transport_jobs:
            machine = transport_job.transporting_vehicle
            if machine not in machines and machine.hours_used > 0:
                emissions_data.append(
                    [
                        machine.machine_id,
                        f"{machine.individualCO2:.1f}",
                        f"{machine.individualNOX:.1f}",
                        "Transport"
                    ]
                )
        emissions_table = Table(emissions_data)

        emissions_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ]
            )
        )

        story.append(emissions_table)

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                f"""
                <b>Total Mission CO_2:</b> {mission.mission_CO2:.1f} kg<br/>
                <b>Total Mission NOx:</b> {mission.mission_NOx:.1f} kg
                """,
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                """
                The selected strategy satisfies mission requirements
                while prioritizing, to the extend of the preferences set, the lowest achievable environmental
                impact within the operational constraints of the fleet.
                """,
                styles["BodyText"],
            )
        )

        doc.build(story)